# Generated by Django 5.2.7 on 2025-10-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'ประเภทงาน (Job)',
                'verbose_name_plural': 'ประเภทงาน (Job)',
            },
        ),
        migrations.CreateModel(
            name='TypeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'ประเภทวิดีโอ',
                'verbose_name_plural': 'ประเภทวิดีโอ',
            },
        ),
        migrations.CreateModel(
            name='Caster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobs', models.ManyToManyField(blank=True, related_name='casters', to='videos.job_type')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video_Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('song_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('facebook', 'Facebook')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('types', models.ManyToManyField(blank=True, related_name='videos', to='videos.typevideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
