# Generated by Django 5.2.7 on 2025-10-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_recommended',
            name='platform',
            field=models.CharField(blank=True, choices=[('Youtube', 'YouTube'), ('TikTok', 'TikTok'), ('Facebook', 'Facebook')], max_length=20, null=True),
        ),
    ]
