# Generated by Django 5.2.7 on 2025-10-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_recommended_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('comments_count', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='caster',
            options={'ordering': ['-created_at'], 'verbose_name': 'Caster', 'verbose_name_plural': 'Casters'},
        ),
        migrations.AlterModelOptions(
            name='video_recommended',
            options={'ordering': ['-created_at'], 'verbose_name': 'วิดีโอแนะนำ', 'verbose_name_plural': 'วิดีโอแนะนำ'},
        ),
        migrations.CreateModel(
            name='YouTubeComment',
            fields=[
                ('comment_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('video_id', models.CharField(db_index=True, max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('author_channel_id', models.CharField(max_length=100)),
                ('author_profile_image', models.URLField(max_length=500)),
                ('author_channel_url', models.URLField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('text_original', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('total_reply_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('can_reply', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'YouTube Comment',
                'verbose_name_plural': 'YouTube Comments',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['video_id', '-published_at'], name='videos_yout_video_i_af337c_idx'), models.Index(fields=['video_id', '-likes'], name='videos_yout_video_i_29a4ea_idx'), models.Index(fields=['-last_synced'], name='videos_yout_last_sy_f0c5af_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('reply_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('author_channel_id', models.CharField(blank=True, max_length=100)),
                ('author_profile_image', models.URLField(max_length=500)),
                ('text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.youtubecomment')),
            ],
            options={
                'verbose_name': 'Comment Reply',
                'verbose_name_plural': 'Comment Replies',
                'ordering': ['published_at'],
            },
        ),
    ]
