# Generated by Django 5.2.7 on 2025-10-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_url_video_song_url_video_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('facebook', 'Facebook')], default='youtube', max_length=20),
        ),
    ]
